# Required
version: 2

# Build all formats
formats: all

# Set the build image to use the most recent version
build:
  os: "ubuntu-22.04"

# Set the python version and requirements
python:
  version: "3"
  # install:
  #   - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Don't use submodules for documentation (readthedocs fails when using submodules)
submodules:
  exclude: all

conda:
  environment: docs/environment.yaml
