# Required
version: 2

# Set the build image to use the latest version
build:
  image: testing
  apt_packages:
    - doxygen

# Build all formats
formats: all

# Set the python version and requirements
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Don't use submodules for documentation (readthedocs fails when using submodules)
submodules:
  exclude: all
