language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
os:
  - linux
  - osx

# Install dependencies
install:
  - pip install -r build_requirements.txt

 # Build the library
script:
  - python3 setup.py sdist bdist_wheel || python setup.py sdist bdist_wheel
  - pip install .
  - pytest
