language: python
os: linux
env:
  global:
    - CIBW_BUILD=cp3?-*
    - CIBW_MANYLINUX_X86_64_IMAGE=manylinux1
    - CIBW_MANYLINUX_I686_IMAGE=manylinux1
    - TWINE_USERNAME=__token__

jobs:
  include:
    - services: docker
    - os: osx
      language: generic
      osx_image: xcode12.4
    - os: windows
      language: bash
      before_install:
        - choco install python --version 3.8.0
        - choco install visualstudio2019community
        - choco install visualstudio2019-workload-nativedesktop
        - export VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools"
        - export PATH="/c/Python38:/c/Python/Scripts:$PATH"

install:
  - python3 -m pip install -r build_requirements.txt || python -m pip install -r build_requirements.txt

script:
  # - python3 setup.py sdist bdist_wheel || python setup.py sdist bdist_wheel
  # - python3 -m pip install . || python -m pip install .
  # - python3 -m pytest || python -m pytest
  - python3 -m cibuildwheel --output-dir ./wheelhouse || python -m cibuildwheel --output-dir ./wheelhouse
