name: docs # doxygen
channels:
  - conda-forge
dependencies:
  - python=3.9
  - doxygen=1.9.1
  - pip
  - pip:
      - sphinx==4.4.0
      - breathe==4.33.1
      - exhale==0.3.1
      - furo==2022.2.14.1
      - pydata-sphinx-theme==0.8.0
      - numpydoc==1.2
      - sphinx-panels==0.6.0
      - regex
