name: docs # doxygen
channels:
  - conda-forge
dependencies:
  - python=3.9
  - doxygen=1.9.1
  - pip
  - pip:
      - sphinx==3.4.3
      - breathe==4.30.0
      - exhale==0.2.3
      - furo==2021.4.11b34
      - pydata-sphinx-theme==0.6.3
      - numpydoc==1.1.0
      - sphinx-panels==0.6.0
