#ifndef LIBRAPID_CORE_MSVC_CONFIG_HPP
#define LIBRAPID_CORE_MSVC_CONFIG_HPP

#define LIBRAPID_INLINE        inline
#define LIBRAPID_ALWAYS_INLINE inline __forceinline

#endif // LIBRAPID_CORE_MSVC_CONFIG_HPP