name: Build (Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  windows_build:
    name: Build LibRapid on Windows
    runs-on: windows-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      # - name: Set Up WSL
      #   uses: Vampire/setup-wsl@v1.2.0

      - name: Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1

      - name: Set Up Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Install Conda things
        run: |
          conda config --add channels conda-forge --force
          conda config --set auto_update_conda false
          conda install --yes --quiet clangdev cmake ninja flang=11.0.1

      # Download an OpenBLAS build
      - name: Download OpenBLAS Build
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-openblas.yaml
          workflow_conclusion: success
          name: OpenBLAS on windows-latest
          path: src/librapid/openblas_install

      - name: Build LibRapid
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
        env:
          LIBRAPID_NO_ARCH: yes