py::class_<librapid::ArrayB>(module, "ArrayB")
	.def(py::init<>())
	.def(py::init<librapid::Extent>())
	.def(py::init<const librapid::ArrayB &>())
	.def(py::init<librapid::internal::traits<librapid::ArrayB>::Scalar>())
	.def("copy", [](const librapid::ArrayB & arr) { return arr.copy(); })
	.def("__getitem__", [](const librapid::ArrayB & arr, int64_t index) { return arr[index]; }, py::arg("index"))
	.def("__setitem__", [](librapid::ArrayB & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayB>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("__setitem__", [](librapid::ArrayB & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayB>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("move_CPU", [](const librapid::ArrayB & arr) { return arr.move<librapid::device::CPU>(); })
	.def("cast_ArrayB", [](const librapid::ArrayB & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayB>::Scalar>(); })
	.def("castMove_ArrayB_CPU", [](const librapid::ArrayB & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayB>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayB", [](const librapid::ArrayB & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayC>::Scalar>(); })
	.def("castMove_ArrayC_CPU", [](const librapid::ArrayB & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayC>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayB", [](const librapid::ArrayB & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF16>::Scalar>(); })
	.def("castMove_ArrayF16_CPU", [](const librapid::ArrayB & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayB", [](const librapid::ArrayB & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF32>::Scalar>(); })
	.def("castMove_ArrayF32_CPU", [](const librapid::ArrayB & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayB", [](const librapid::ArrayB & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF64>::Scalar>(); })
	.def("castMove_ArrayF64_CPU", [](const librapid::ArrayB & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF64>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayB", [](const librapid::ArrayB & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI16>::Scalar>(); })
	.def("castMove_ArrayI16_CPU", [](const librapid::ArrayB & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayB", [](const librapid::ArrayB & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI32>::Scalar>(); })
	.def("castMove_ArrayI32_CPU", [](const librapid::ArrayB & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayB", [](const librapid::ArrayB & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI64>::Scalar>(); })
	.def("castMove_ArrayI64_CPU", [](const librapid::ArrayB & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI64>::Scalar, librapid::device::CPU>(); })
	.def("__or__", [](const librapid::ArrayB & this_, const librapid::ArrayB & other) { return this_ | other; }, py::arg("other"))
	.def("__and__", [](const librapid::ArrayB & this_, const librapid::ArrayB & other) { return this_ & other; }, py::arg("other"))
	.def("__xor__", [](const librapid::ArrayB & this_, const librapid::ArrayB & other) { return this_ ^ other; }, py::arg("other"))
	.def("__invert__", [](const librapid::ArrayB & this_) { return ~this_; })
	.def("transpose", [](librapid::ArrayB & this_, const librapid::Extent & order) { this_.transpose(order); }, py::arg("order") = librapid::Extent({}))
	.def("transposed", [](const librapid::ArrayB & this_, const librapid::Extent & order) { return this_.transposed(order); }, py::arg("order") = librapid::Extent({}))
	.def("dot", [](const librapid::ArrayB & this_, const librapid::ArrayB & other) { return this_.dot(other); }, py::arg("other"))
	.def("str", [](const librapid::ArrayB & this_, const std::string & format, const std::string & delim, int64_t stripWidth, int64_t beforePoint, int64_t afterPoint, int64_t depth) { return this_.str(format, delim, stripWidth, beforePoint, afterPoint, depth); }, py::arg("format") = std::string("{}"), py::arg("delim") = std::string(" "), py::arg("stripWidth") = int64_t(-1), py::arg("beforePoint") = int64_t(-1), py::arg("afterPoint") = int64_t(-1), py::arg("depth") = int64_t(0))
	.def("__str__", [](const librapid::ArrayB & this_) { return this_.str(); })
	.def("__repr__", [](const librapid::ArrayB & this_) { return "<librapid::ArrayB\n" + this_.str("{}", ",") + "\n>"; });
py::class_<librapid::ArrayC>(module, "ArrayC")
	.def(py::init<>())
	.def(py::init<librapid::Extent>())
	.def(py::init<const librapid::ArrayC &>())
	.def(py::init<librapid::internal::traits<librapid::ArrayC>::Scalar>())
	.def("copy", [](const librapid::ArrayC & arr) { return arr.copy(); })
	.def("__getitem__", [](const librapid::ArrayC & arr, int64_t index) { return arr[index]; }, py::arg("index"))
	.def("__setitem__", [](librapid::ArrayC & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayC>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("__setitem__", [](librapid::ArrayC & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayC>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("move_CPU", [](const librapid::ArrayC & arr) { return arr.move<librapid::device::CPU>(); })
	.def("cast_ArrayC", [](const librapid::ArrayC & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayB>::Scalar>(); })
	.def("castMove_ArrayB_CPU", [](const librapid::ArrayC & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayB>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayC", [](const librapid::ArrayC & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayC>::Scalar>(); })
	.def("castMove_ArrayC_CPU", [](const librapid::ArrayC & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayC>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayC", [](const librapid::ArrayC & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF16>::Scalar>(); })
	.def("castMove_ArrayF16_CPU", [](const librapid::ArrayC & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayC", [](const librapid::ArrayC & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF32>::Scalar>(); })
	.def("castMove_ArrayF32_CPU", [](const librapid::ArrayC & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayC", [](const librapid::ArrayC & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF64>::Scalar>(); })
	.def("castMove_ArrayF64_CPU", [](const librapid::ArrayC & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF64>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayC", [](const librapid::ArrayC & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI16>::Scalar>(); })
	.def("castMove_ArrayI16_CPU", [](const librapid::ArrayC & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayC", [](const librapid::ArrayC & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI32>::Scalar>(); })
	.def("castMove_ArrayI32_CPU", [](const librapid::ArrayC & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayC", [](const librapid::ArrayC & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI64>::Scalar>(); })
	.def("castMove_ArrayI64_CPU", [](const librapid::ArrayC & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI64>::Scalar, librapid::device::CPU>(); })
	.def("__add__", [](const librapid::ArrayC & this_, const librapid::ArrayC & other) { return this_ + other; }, py::arg("other"))
	.def("__add__", [](const librapid::ArrayC & this_, typename librapid::internal::traits<librapid::ArrayC>::Scalar other) { return this_ + other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayC & this_, const librapid::ArrayC & other) { return this_ - other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayC & this_, typename librapid::internal::traits<librapid::ArrayC>::Scalar other) { return this_ - other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayC & this_, const librapid::ArrayC & other) { return this_ * other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayC & this_, typename librapid::internal::traits<librapid::ArrayC>::Scalar other) { return this_ * other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayC & this_, const librapid::ArrayC & other) { return this_ / other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayC & this_, typename librapid::internal::traits<librapid::ArrayC>::Scalar other) { return this_ / other; }, py::arg("other"))
	.def("__or__", [](const librapid::ArrayC & this_, const librapid::ArrayC & other) { return this_ | other; }, py::arg("other"))
	.def("__and__", [](const librapid::ArrayC & this_, const librapid::ArrayC & other) { return this_ & other; }, py::arg("other"))
	.def("__xor__", [](const librapid::ArrayC & this_, const librapid::ArrayC & other) { return this_ ^ other; }, py::arg("other"))
	.def("__neg__", [](const librapid::ArrayC & this_) { return -this_; })
	.def("transpose", [](librapid::ArrayC & this_, const librapid::Extent & order) { this_.transpose(order); }, py::arg("order") = librapid::Extent({}))
	.def("transposed", [](const librapid::ArrayC & this_, const librapid::Extent & order) { return this_.transposed(order); }, py::arg("order") = librapid::Extent({}))
	.def("dot", [](const librapid::ArrayC & this_, const librapid::ArrayC & other) { return this_.dot(other); }, py::arg("other"))
	.def("str", [](const librapid::ArrayC & this_, const std::string & format, const std::string & delim, int64_t stripWidth, int64_t beforePoint, int64_t afterPoint, int64_t depth) { return this_.str(format, delim, stripWidth, beforePoint, afterPoint, depth); }, py::arg("format") = std::string("{}"), py::arg("delim") = std::string(" "), py::arg("stripWidth") = int64_t(-1), py::arg("beforePoint") = int64_t(-1), py::arg("afterPoint") = int64_t(-1), py::arg("depth") = int64_t(0))
	.def("__str__", [](const librapid::ArrayC & this_) { return this_.str(); })
	.def("__repr__", [](const librapid::ArrayC & this_) { return "<librapid::ArrayC\n" + this_.str("{}", ",") + "\n>"; });
py::class_<librapid::ArrayF16>(module, "ArrayF16")
	.def(py::init<>())
	.def(py::init<librapid::Extent>())
	.def(py::init<const librapid::ArrayF16 &>())
	.def(py::init<librapid::internal::traits<librapid::ArrayF16>::Scalar>())
	.def("copy", [](const librapid::ArrayF16 & arr) { return arr.copy(); })
	.def("__getitem__", [](const librapid::ArrayF16 & arr, int64_t index) { return arr[index]; }, py::arg("index"))
	.def("__setitem__", [](librapid::ArrayF16 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayF16>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("__setitem__", [](librapid::ArrayF16 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayF16>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("move_CPU", [](const librapid::ArrayF16 & arr) { return arr.move<librapid::device::CPU>(); })
	.def("cast_ArrayF16", [](const librapid::ArrayF16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayB>::Scalar>(); })
	.def("castMove_ArrayB_CPU", [](const librapid::ArrayF16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayB>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF16", [](const librapid::ArrayF16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayC>::Scalar>(); })
	.def("castMove_ArrayC_CPU", [](const librapid::ArrayF16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayC>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF16", [](const librapid::ArrayF16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF16>::Scalar>(); })
	.def("castMove_ArrayF16_CPU", [](const librapid::ArrayF16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF16", [](const librapid::ArrayF16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF32>::Scalar>(); })
	.def("castMove_ArrayF32_CPU", [](const librapid::ArrayF16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF16", [](const librapid::ArrayF16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF64>::Scalar>(); })
	.def("castMove_ArrayF64_CPU", [](const librapid::ArrayF16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF64>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF16", [](const librapid::ArrayF16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI16>::Scalar>(); })
	.def("castMove_ArrayI16_CPU", [](const librapid::ArrayF16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF16", [](const librapid::ArrayF16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI32>::Scalar>(); })
	.def("castMove_ArrayI32_CPU", [](const librapid::ArrayF16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF16", [](const librapid::ArrayF16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI64>::Scalar>(); })
	.def("castMove_ArrayI64_CPU", [](const librapid::ArrayF16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI64>::Scalar, librapid::device::CPU>(); })
	.def("__add__", [](const librapid::ArrayF16 & this_, const librapid::ArrayF16 & other) { return this_ + other; }, py::arg("other"))
	.def("__add__", [](const librapid::ArrayF16 & this_, typename librapid::internal::traits<librapid::ArrayF16>::Scalar other) { return this_ + other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayF16 & this_, const librapid::ArrayF16 & other) { return this_ - other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayF16 & this_, typename librapid::internal::traits<librapid::ArrayF16>::Scalar other) { return this_ - other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayF16 & this_, const librapid::ArrayF16 & other) { return this_ * other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayF16 & this_, typename librapid::internal::traits<librapid::ArrayF16>::Scalar other) { return this_ * other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayF16 & this_, const librapid::ArrayF16 & other) { return this_ / other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayF16 & this_, typename librapid::internal::traits<librapid::ArrayF16>::Scalar other) { return this_ / other; }, py::arg("other"))
	.def("transpose", [](librapid::ArrayF16 & this_, const librapid::Extent & order) { this_.transpose(order); }, py::arg("order") = librapid::Extent({}))
	.def("transposed", [](const librapid::ArrayF16 & this_, const librapid::Extent & order) { return this_.transposed(order); }, py::arg("order") = librapid::Extent({}))
	.def("dot", [](const librapid::ArrayF16 & this_, const librapid::ArrayF16 & other) { return this_.dot(other); }, py::arg("other"))
	.def("str", [](const librapid::ArrayF16 & this_, const std::string & format, const std::string & delim, int64_t stripWidth, int64_t beforePoint, int64_t afterPoint, int64_t depth) { return this_.str(format, delim, stripWidth, beforePoint, afterPoint, depth); }, py::arg("format") = std::string("{}"), py::arg("delim") = std::string(" "), py::arg("stripWidth") = int64_t(-1), py::arg("beforePoint") = int64_t(-1), py::arg("afterPoint") = int64_t(-1), py::arg("depth") = int64_t(0))
	.def("__str__", [](const librapid::ArrayF16 & this_) { return this_.str(); })
	.def("__repr__", [](const librapid::ArrayF16 & this_) { return "<librapid::ArrayF16\n" + this_.str("{}", ",") + "\n>"; });
py::class_<librapid::ArrayF32>(module, "ArrayF32")
	.def(py::init<>())
	.def(py::init<librapid::Extent>())
	.def(py::init<const librapid::ArrayF32 &>())
	.def(py::init<librapid::internal::traits<librapid::ArrayF32>::Scalar>())
	.def("copy", [](const librapid::ArrayF32 & arr) { return arr.copy(); })
	.def("__getitem__", [](const librapid::ArrayF32 & arr, int64_t index) { return arr[index]; }, py::arg("index"))
	.def("__setitem__", [](librapid::ArrayF32 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayF32>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("__setitem__", [](librapid::ArrayF32 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayF32>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("move_CPU", [](const librapid::ArrayF32 & arr) { return arr.move<librapid::device::CPU>(); })
	.def("cast_ArrayF32", [](const librapid::ArrayF32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayB>::Scalar>(); })
	.def("castMove_ArrayB_CPU", [](const librapid::ArrayF32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayB>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF32", [](const librapid::ArrayF32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayC>::Scalar>(); })
	.def("castMove_ArrayC_CPU", [](const librapid::ArrayF32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayC>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF32", [](const librapid::ArrayF32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF16>::Scalar>(); })
	.def("castMove_ArrayF16_CPU", [](const librapid::ArrayF32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF32", [](const librapid::ArrayF32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF32>::Scalar>(); })
	.def("castMove_ArrayF32_CPU", [](const librapid::ArrayF32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF32", [](const librapid::ArrayF32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF64>::Scalar>(); })
	.def("castMove_ArrayF64_CPU", [](const librapid::ArrayF32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF64>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF32", [](const librapid::ArrayF32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI16>::Scalar>(); })
	.def("castMove_ArrayI16_CPU", [](const librapid::ArrayF32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF32", [](const librapid::ArrayF32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI32>::Scalar>(); })
	.def("castMove_ArrayI32_CPU", [](const librapid::ArrayF32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF32", [](const librapid::ArrayF32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI64>::Scalar>(); })
	.def("castMove_ArrayI64_CPU", [](const librapid::ArrayF32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI64>::Scalar, librapid::device::CPU>(); })
	.def("__add__", [](const librapid::ArrayF32 & this_, const librapid::ArrayF32 & other) { return this_ + other; }, py::arg("other"))
	.def("__add__", [](const librapid::ArrayF32 & this_, typename librapid::internal::traits<librapid::ArrayF32>::Scalar other) { return this_ + other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayF32 & this_, const librapid::ArrayF32 & other) { return this_ - other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayF32 & this_, typename librapid::internal::traits<librapid::ArrayF32>::Scalar other) { return this_ - other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayF32 & this_, const librapid::ArrayF32 & other) { return this_ * other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayF32 & this_, typename librapid::internal::traits<librapid::ArrayF32>::Scalar other) { return this_ * other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayF32 & this_, const librapid::ArrayF32 & other) { return this_ / other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayF32 & this_, typename librapid::internal::traits<librapid::ArrayF32>::Scalar other) { return this_ / other; }, py::arg("other"))
	.def("transpose", [](librapid::ArrayF32 & this_, const librapid::Extent & order) { this_.transpose(order); }, py::arg("order") = librapid::Extent({}))
	.def("transposed", [](const librapid::ArrayF32 & this_, const librapid::Extent & order) { return this_.transposed(order); }, py::arg("order") = librapid::Extent({}))
	.def("dot", [](const librapid::ArrayF32 & this_, const librapid::ArrayF32 & other) { return this_.dot(other); }, py::arg("other"))
	.def("str", [](const librapid::ArrayF32 & this_, const std::string & format, const std::string & delim, int64_t stripWidth, int64_t beforePoint, int64_t afterPoint, int64_t depth) { return this_.str(format, delim, stripWidth, beforePoint, afterPoint, depth); }, py::arg("format") = std::string("{}"), py::arg("delim") = std::string(" "), py::arg("stripWidth") = int64_t(-1), py::arg("beforePoint") = int64_t(-1), py::arg("afterPoint") = int64_t(-1), py::arg("depth") = int64_t(0))
	.def("__str__", [](const librapid::ArrayF32 & this_) { return this_.str(); })
	.def("__repr__", [](const librapid::ArrayF32 & this_) { return "<librapid::ArrayF32\n" + this_.str("{}", ",") + "\n>"; });
py::class_<librapid::ArrayF64>(module, "ArrayF64")
	.def(py::init<>())
	.def(py::init<librapid::Extent>())
	.def(py::init<const librapid::ArrayF64 &>())
	.def(py::init<librapid::internal::traits<librapid::ArrayF64>::Scalar>())
	.def("copy", [](const librapid::ArrayF64 & arr) { return arr.copy(); })
	.def("__getitem__", [](const librapid::ArrayF64 & arr, int64_t index) { return arr[index]; }, py::arg("index"))
	.def("__setitem__", [](librapid::ArrayF64 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayF64>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("__setitem__", [](librapid::ArrayF64 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayF64>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("move_CPU", [](const librapid::ArrayF64 & arr) { return arr.move<librapid::device::CPU>(); })
	.def("cast_ArrayF64", [](const librapid::ArrayF64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayB>::Scalar>(); })
	.def("castMove_ArrayB_CPU", [](const librapid::ArrayF64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayB>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF64", [](const librapid::ArrayF64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayC>::Scalar>(); })
	.def("castMove_ArrayC_CPU", [](const librapid::ArrayF64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayC>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF64", [](const librapid::ArrayF64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF16>::Scalar>(); })
	.def("castMove_ArrayF16_CPU", [](const librapid::ArrayF64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF64", [](const librapid::ArrayF64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF32>::Scalar>(); })
	.def("castMove_ArrayF32_CPU", [](const librapid::ArrayF64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF64", [](const librapid::ArrayF64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF64>::Scalar>(); })
	.def("castMove_ArrayF64_CPU", [](const librapid::ArrayF64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF64>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF64", [](const librapid::ArrayF64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI16>::Scalar>(); })
	.def("castMove_ArrayI16_CPU", [](const librapid::ArrayF64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF64", [](const librapid::ArrayF64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI32>::Scalar>(); })
	.def("castMove_ArrayI32_CPU", [](const librapid::ArrayF64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayF64", [](const librapid::ArrayF64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI64>::Scalar>(); })
	.def("castMove_ArrayI64_CPU", [](const librapid::ArrayF64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI64>::Scalar, librapid::device::CPU>(); })
	.def("__add__", [](const librapid::ArrayF64 & this_, const librapid::ArrayF64 & other) { return this_ + other; }, py::arg("other"))
	.def("__add__", [](const librapid::ArrayF64 & this_, typename librapid::internal::traits<librapid::ArrayF64>::Scalar other) { return this_ + other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayF64 & this_, const librapid::ArrayF64 & other) { return this_ - other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayF64 & this_, typename librapid::internal::traits<librapid::ArrayF64>::Scalar other) { return this_ - other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayF64 & this_, const librapid::ArrayF64 & other) { return this_ * other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayF64 & this_, typename librapid::internal::traits<librapid::ArrayF64>::Scalar other) { return this_ * other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayF64 & this_, const librapid::ArrayF64 & other) { return this_ / other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayF64 & this_, typename librapid::internal::traits<librapid::ArrayF64>::Scalar other) { return this_ / other; }, py::arg("other"))
	.def("transpose", [](librapid::ArrayF64 & this_, const librapid::Extent & order) { this_.transpose(order); }, py::arg("order") = librapid::Extent({}))
	.def("transposed", [](const librapid::ArrayF64 & this_, const librapid::Extent & order) { return this_.transposed(order); }, py::arg("order") = librapid::Extent({}))
	.def("dot", [](const librapid::ArrayF64 & this_, const librapid::ArrayF64 & other) { return this_.dot(other); }, py::arg("other"))
	.def("str", [](const librapid::ArrayF64 & this_, const std::string & format, const std::string & delim, int64_t stripWidth, int64_t beforePoint, int64_t afterPoint, int64_t depth) { return this_.str(format, delim, stripWidth, beforePoint, afterPoint, depth); }, py::arg("format") = std::string("{}"), py::arg("delim") = std::string(" "), py::arg("stripWidth") = int64_t(-1), py::arg("beforePoint") = int64_t(-1), py::arg("afterPoint") = int64_t(-1), py::arg("depth") = int64_t(0))
	.def("__str__", [](const librapid::ArrayF64 & this_) { return this_.str(); })
	.def("__repr__", [](const librapid::ArrayF64 & this_) { return "<librapid::ArrayF64\n" + this_.str("{}", ",") + "\n>"; });
py::class_<librapid::ArrayI16>(module, "ArrayI16")
	.def(py::init<>())
	.def(py::init<librapid::Extent>())
	.def(py::init<const librapid::ArrayI16 &>())
	.def(py::init<librapid::internal::traits<librapid::ArrayI16>::Scalar>())
	.def("copy", [](const librapid::ArrayI16 & arr) { return arr.copy(); })
	.def("__getitem__", [](const librapid::ArrayI16 & arr, int64_t index) { return arr[index]; }, py::arg("index"))
	.def("__setitem__", [](librapid::ArrayI16 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayI16>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("__setitem__", [](librapid::ArrayI16 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayI16>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("move_CPU", [](const librapid::ArrayI16 & arr) { return arr.move<librapid::device::CPU>(); })
	.def("cast_ArrayI16", [](const librapid::ArrayI16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayB>::Scalar>(); })
	.def("castMove_ArrayB_CPU", [](const librapid::ArrayI16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayB>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI16", [](const librapid::ArrayI16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayC>::Scalar>(); })
	.def("castMove_ArrayC_CPU", [](const librapid::ArrayI16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayC>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI16", [](const librapid::ArrayI16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF16>::Scalar>(); })
	.def("castMove_ArrayF16_CPU", [](const librapid::ArrayI16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI16", [](const librapid::ArrayI16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF32>::Scalar>(); })
	.def("castMove_ArrayF32_CPU", [](const librapid::ArrayI16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI16", [](const librapid::ArrayI16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF64>::Scalar>(); })
	.def("castMove_ArrayF64_CPU", [](const librapid::ArrayI16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF64>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI16", [](const librapid::ArrayI16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI16>::Scalar>(); })
	.def("castMove_ArrayI16_CPU", [](const librapid::ArrayI16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI16", [](const librapid::ArrayI16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI32>::Scalar>(); })
	.def("castMove_ArrayI32_CPU", [](const librapid::ArrayI16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI16", [](const librapid::ArrayI16 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI64>::Scalar>(); })
	.def("castMove_ArrayI64_CPU", [](const librapid::ArrayI16 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI64>::Scalar, librapid::device::CPU>(); })
	.def("__add__", [](const librapid::ArrayI16 & this_, const librapid::ArrayI16 & other) { return this_ + other; }, py::arg("other"))
	.def("__add__", [](const librapid::ArrayI16 & this_, typename librapid::internal::traits<librapid::ArrayI16>::Scalar other) { return this_ + other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayI16 & this_, const librapid::ArrayI16 & other) { return this_ - other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayI16 & this_, typename librapid::internal::traits<librapid::ArrayI16>::Scalar other) { return this_ - other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayI16 & this_, const librapid::ArrayI16 & other) { return this_ * other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayI16 & this_, typename librapid::internal::traits<librapid::ArrayI16>::Scalar other) { return this_ * other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayI16 & this_, const librapid::ArrayI16 & other) { return this_ / other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayI16 & this_, typename librapid::internal::traits<librapid::ArrayI16>::Scalar other) { return this_ / other; }, py::arg("other"))
	.def("__or__", [](const librapid::ArrayI16 & this_, const librapid::ArrayI16 & other) { return this_ | other; }, py::arg("other"))
	.def("__and__", [](const librapid::ArrayI16 & this_, const librapid::ArrayI16 & other) { return this_ & other; }, py::arg("other"))
	.def("__xor__", [](const librapid::ArrayI16 & this_, const librapid::ArrayI16 & other) { return this_ ^ other; }, py::arg("other"))
	.def("__neg__", [](const librapid::ArrayI16 & this_) { return -this_; })
	.def("transpose", [](librapid::ArrayI16 & this_, const librapid::Extent & order) { this_.transpose(order); }, py::arg("order") = librapid::Extent({}))
	.def("transposed", [](const librapid::ArrayI16 & this_, const librapid::Extent & order) { return this_.transposed(order); }, py::arg("order") = librapid::Extent({}))
	.def("dot", [](const librapid::ArrayI16 & this_, const librapid::ArrayI16 & other) { return this_.dot(other); }, py::arg("other"))
	.def("str", [](const librapid::ArrayI16 & this_, const std::string & format, const std::string & delim, int64_t stripWidth, int64_t beforePoint, int64_t afterPoint, int64_t depth) { return this_.str(format, delim, stripWidth, beforePoint, afterPoint, depth); }, py::arg("format") = std::string("{}"), py::arg("delim") = std::string(" "), py::arg("stripWidth") = int64_t(-1), py::arg("beforePoint") = int64_t(-1), py::arg("afterPoint") = int64_t(-1), py::arg("depth") = int64_t(0))
	.def("__str__", [](const librapid::ArrayI16 & this_) { return this_.str(); })
	.def("__repr__", [](const librapid::ArrayI16 & this_) { return "<librapid::ArrayI16\n" + this_.str("{}", ",") + "\n>"; });
py::class_<librapid::ArrayI32>(module, "ArrayI32")
	.def(py::init<>())
	.def(py::init<librapid::Extent>())
	.def(py::init<const librapid::ArrayI32 &>())
	.def(py::init<librapid::internal::traits<librapid::ArrayI32>::Scalar>())
	.def("copy", [](const librapid::ArrayI32 & arr) { return arr.copy(); })
	.def("__getitem__", [](const librapid::ArrayI32 & arr, int64_t index) { return arr[index]; }, py::arg("index"))
	.def("__setitem__", [](librapid::ArrayI32 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayI32>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("__setitem__", [](librapid::ArrayI32 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayI32>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("move_CPU", [](const librapid::ArrayI32 & arr) { return arr.move<librapid::device::CPU>(); })
	.def("cast_ArrayI32", [](const librapid::ArrayI32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayB>::Scalar>(); })
	.def("castMove_ArrayB_CPU", [](const librapid::ArrayI32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayB>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI32", [](const librapid::ArrayI32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayC>::Scalar>(); })
	.def("castMove_ArrayC_CPU", [](const librapid::ArrayI32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayC>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI32", [](const librapid::ArrayI32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF16>::Scalar>(); })
	.def("castMove_ArrayF16_CPU", [](const librapid::ArrayI32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI32", [](const librapid::ArrayI32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF32>::Scalar>(); })
	.def("castMove_ArrayF32_CPU", [](const librapid::ArrayI32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI32", [](const librapid::ArrayI32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF64>::Scalar>(); })
	.def("castMove_ArrayF64_CPU", [](const librapid::ArrayI32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF64>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI32", [](const librapid::ArrayI32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI16>::Scalar>(); })
	.def("castMove_ArrayI16_CPU", [](const librapid::ArrayI32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI32", [](const librapid::ArrayI32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI32>::Scalar>(); })
	.def("castMove_ArrayI32_CPU", [](const librapid::ArrayI32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI32", [](const librapid::ArrayI32 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI64>::Scalar>(); })
	.def("castMove_ArrayI64_CPU", [](const librapid::ArrayI32 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI64>::Scalar, librapid::device::CPU>(); })
	.def("__add__", [](const librapid::ArrayI32 & this_, const librapid::ArrayI32 & other) { return this_ + other; }, py::arg("other"))
	.def("__add__", [](const librapid::ArrayI32 & this_, typename librapid::internal::traits<librapid::ArrayI32>::Scalar other) { return this_ + other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayI32 & this_, const librapid::ArrayI32 & other) { return this_ - other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayI32 & this_, typename librapid::internal::traits<librapid::ArrayI32>::Scalar other) { return this_ - other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayI32 & this_, const librapid::ArrayI32 & other) { return this_ * other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayI32 & this_, typename librapid::internal::traits<librapid::ArrayI32>::Scalar other) { return this_ * other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayI32 & this_, const librapid::ArrayI32 & other) { return this_ / other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayI32 & this_, typename librapid::internal::traits<librapid::ArrayI32>::Scalar other) { return this_ / other; }, py::arg("other"))
	.def("__or__", [](const librapid::ArrayI32 & this_, const librapid::ArrayI32 & other) { return this_ | other; }, py::arg("other"))
	.def("__and__", [](const librapid::ArrayI32 & this_, const librapid::ArrayI32 & other) { return this_ & other; }, py::arg("other"))
	.def("__xor__", [](const librapid::ArrayI32 & this_, const librapid::ArrayI32 & other) { return this_ ^ other; }, py::arg("other"))
	.def("__neg__", [](const librapid::ArrayI32 & this_) { return -this_; })
	.def("transpose", [](librapid::ArrayI32 & this_, const librapid::Extent & order) { this_.transpose(order); }, py::arg("order") = librapid::Extent({}))
	.def("transposed", [](const librapid::ArrayI32 & this_, const librapid::Extent & order) { return this_.transposed(order); }, py::arg("order") = librapid::Extent({}))
	.def("dot", [](const librapid::ArrayI32 & this_, const librapid::ArrayI32 & other) { return this_.dot(other); }, py::arg("other"))
	.def("str", [](const librapid::ArrayI32 & this_, const std::string & format, const std::string & delim, int64_t stripWidth, int64_t beforePoint, int64_t afterPoint, int64_t depth) { return this_.str(format, delim, stripWidth, beforePoint, afterPoint, depth); }, py::arg("format") = std::string("{}"), py::arg("delim") = std::string(" "), py::arg("stripWidth") = int64_t(-1), py::arg("beforePoint") = int64_t(-1), py::arg("afterPoint") = int64_t(-1), py::arg("depth") = int64_t(0))
	.def("__str__", [](const librapid::ArrayI32 & this_) { return this_.str(); })
	.def("__repr__", [](const librapid::ArrayI32 & this_) { return "<librapid::ArrayI32\n" + this_.str("{}", ",") + "\n>"; });
py::class_<librapid::ArrayI64>(module, "ArrayI64")
	.def(py::init<>())
	.def(py::init<librapid::Extent>())
	.def(py::init<const librapid::ArrayI64 &>())
	.def(py::init<librapid::internal::traits<librapid::ArrayI64>::Scalar>())
	.def("copy", [](const librapid::ArrayI64 & arr) { return arr.copy(); })
	.def("__getitem__", [](const librapid::ArrayI64 & arr, int64_t index) { return arr[index]; }, py::arg("index"))
	.def("__setitem__", [](librapid::ArrayI64 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayI64>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("__setitem__", [](librapid::ArrayI64 & arr, int64_t index, typename librapid::internal::traits<librapid::ArrayI64>::Scalar val) { arr[index] = val; }, py::arg("index"), py::arg("val"))
	.def("move_CPU", [](const librapid::ArrayI64 & arr) { return arr.move<librapid::device::CPU>(); })
	.def("cast_ArrayI64", [](const librapid::ArrayI64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayB>::Scalar>(); })
	.def("castMove_ArrayB_CPU", [](const librapid::ArrayI64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayB>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI64", [](const librapid::ArrayI64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayC>::Scalar>(); })
	.def("castMove_ArrayC_CPU", [](const librapid::ArrayI64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayC>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI64", [](const librapid::ArrayI64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF16>::Scalar>(); })
	.def("castMove_ArrayF16_CPU", [](const librapid::ArrayI64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI64", [](const librapid::ArrayI64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF32>::Scalar>(); })
	.def("castMove_ArrayF32_CPU", [](const librapid::ArrayI64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI64", [](const librapid::ArrayI64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayF64>::Scalar>(); })
	.def("castMove_ArrayF64_CPU", [](const librapid::ArrayI64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayF64>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI64", [](const librapid::ArrayI64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI16>::Scalar>(); })
	.def("castMove_ArrayI16_CPU", [](const librapid::ArrayI64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI16>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI64", [](const librapid::ArrayI64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI32>::Scalar>(); })
	.def("castMove_ArrayI32_CPU", [](const librapid::ArrayI64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI32>::Scalar, librapid::device::CPU>(); })
	.def("cast_ArrayI64", [](const librapid::ArrayI64 & this_) { return this_.cast<typename librapid::internal::traits<librapid::ArrayI64>::Scalar>(); })
	.def("castMove_ArrayI64_CPU", [](const librapid::ArrayI64 & this_) { return this_.castMove<typename librapid::internal::traits<librapid::ArrayI64>::Scalar, librapid::device::CPU>(); })
	.def("__add__", [](const librapid::ArrayI64 & this_, const librapid::ArrayI64 & other) { return this_ + other; }, py::arg("other"))
	.def("__add__", [](const librapid::ArrayI64 & this_, typename librapid::internal::traits<librapid::ArrayI64>::Scalar other) { return this_ + other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayI64 & this_, const librapid::ArrayI64 & other) { return this_ - other; }, py::arg("other"))
	.def("__sub__", [](const librapid::ArrayI64 & this_, typename librapid::internal::traits<librapid::ArrayI64>::Scalar other) { return this_ - other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayI64 & this_, const librapid::ArrayI64 & other) { return this_ * other; }, py::arg("other"))
	.def("__mul__", [](const librapid::ArrayI64 & this_, typename librapid::internal::traits<librapid::ArrayI64>::Scalar other) { return this_ * other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayI64 & this_, const librapid::ArrayI64 & other) { return this_ / other; }, py::arg("other"))
	.def("__div__", [](const librapid::ArrayI64 & this_, typename librapid::internal::traits<librapid::ArrayI64>::Scalar other) { return this_ / other; }, py::arg("other"))
	.def("__or__", [](const librapid::ArrayI64 & this_, const librapid::ArrayI64 & other) { return this_ | other; }, py::arg("other"))
	.def("__and__", [](const librapid::ArrayI64 & this_, const librapid::ArrayI64 & other) { return this_ & other; }, py::arg("other"))
	.def("__xor__", [](const librapid::ArrayI64 & this_, const librapid::ArrayI64 & other) { return this_ ^ other; }, py::arg("other"))
	.def("__neg__", [](const librapid::ArrayI64 & this_) { return -this_; })
	.def("transpose", [](librapid::ArrayI64 & this_, const librapid::Extent & order) { this_.transpose(order); }, py::arg("order") = librapid::Extent({}))
	.def("transposed", [](const librapid::ArrayI64 & this_, const librapid::Extent & order) { return this_.transposed(order); }, py::arg("order") = librapid::Extent({}))
	.def("dot", [](const librapid::ArrayI64 & this_, const librapid::ArrayI64 & other) { return this_.dot(other); }, py::arg("other"))
	.def("str", [](const librapid::ArrayI64 & this_, const std::string & format, const std::string & delim, int64_t stripWidth, int64_t beforePoint, int64_t afterPoint, int64_t depth) { return this_.str(format, delim, stripWidth, beforePoint, afterPoint, depth); }, py::arg("format") = std::string("{}"), py::arg("delim") = std::string(" "), py::arg("stripWidth") = int64_t(-1), py::arg("beforePoint") = int64_t(-1), py::arg("afterPoint") = int64_t(-1), py::arg("depth") = int64_t(0))
	.def("__str__", [](const librapid::ArrayI64 & this_) { return this_.str(); })
	.def("__repr__", [](const librapid::ArrayI64 & this_) { return "<librapid::ArrayI64\n" + this_.str("{}", ",") + "\n>"; });
