var dir_a1c2fae230ad14e5d6980a50e35c56b4 =
[
    [ "acxpby.h", "level1extensions_2acxpby_8h.html", "level1extensions_2acxpby_8h" ],
    [ "acxpy.h", "level1extensions_2acxpy_8h.html", "level1extensions_2acxpy_8h" ],
    [ "asum1.h", "asum1_8h.html", "asum1_8h" ],
    [ "axpby.h", "level1extensions_2axpby_8h.html", "level1extensions_2axpby_8h" ],
    [ "axpy.h", "level1extensions_2axpy_8h.html", "level1extensions_2axpy_8h" ],
    [ "ccopy.h", "level1extensions_2ccopy_8h.html", "level1extensions_2ccopy_8h" ],
    [ "dot.h", "level1extensions_2dot_8h.html", "level1extensions_2dot_8h" ],
    [ "gbaxpby.h", "gbaxpby_8h.html", "gbaxpby_8h" ],
    [ "gbaxpy.h", "gbaxpy_8h.html", "gbaxpy_8h" ],
    [ "gbcopy.h", "gbcopy_8h.html", "gbcopy_8h" ],
    [ "gbcotr.h", "gbcotr_8h.html", "gbcotr_8h" ],
    [ "gbscal.h", "gbscal_8h.html", "gbscal_8h" ],
    [ "geaxpby.h", "geaxpby_8h.html", "geaxpby_8h" ],
    [ "geaxpy.h", "level1extensions_2geaxpy_8h.html", "level1extensions_2geaxpy_8h" ],
    [ "gecopy.h", "level1extensions_2gecopy_8h.html", "level1extensions_2gecopy_8h" ],
    [ "gecotr.h", "gecotr_8h.html", "gecotr_8h" ],
    [ "geraxpy.h", "geraxpy_8h.html", "geraxpy_8h" ],
    [ "gerscal.h", "level1extensions_2gerscal_8h.html", "level1extensions_2gerscal_8h" ],
    [ "gescal.h", "level1extensions_2gescal_8h.html", "level1extensions_2gescal_8h" ],
    [ "geswap.h", "geswap_8h.html", "geswap_8h" ],
    [ "hescal.h", "hescal_8h.html", "hescal_8h" ],
    [ "imax1.h", "imax1_8h.html", "imax1_8h" ],
    [ "level1extensions.h", "level1extensions_8h.html", null ],
    [ "racxpy.h", "racxpy_8h.html", "racxpy_8h" ],
    [ "raxpy.h", "raxpy_8h.html", "raxpy_8h" ],
    [ "rscal.h", "level1extensions_2rscal_8h.html", "level1extensions_2rscal_8h" ],
    [ "syscal.h", "syscal_8h.html", "syscal_8h" ],
    [ "tpaxpby.h", "tpaxpby_8h.html", "tpaxpby_8h" ],
    [ "tpaxpy.h", "tpaxpy_8h.html", "tpaxpy_8h" ],
    [ "tpcopy.h", "tpcopy_8h.html", "tpcopy_8h" ],
    [ "tpscal.h", "tpscal_8h.html", "tpscal_8h" ],
    [ "traxpby.h", "traxpby_8h.html", "traxpby_8h" ],
    [ "traxpy.h", "traxpy_8h.html", "traxpy_8h" ],
    [ "trcopy.h", "trcopy_8h.html", "trcopy_8h" ],
    [ "trscal.h", "trscal_8h.html", "trscal_8h" ]
];