name: Build Documentation

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # On Linux, the apt package doesn't build the search engine for some reason.
      # By building and installing doxygen ourselves, we can ensure that the documentation
      # has a working search engine.
      - name: Build Doxygen
        run: |
          git clone --recursive https://github.com/doxygen/doxygen.git
          cd doxygen
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --parallel
          sudo make install

      - name: Install Requirements
        run: |
          sudo apt-get install -y texlive-full
          cd docs
          pip install -r requirements.txt

      - name: Build Documentation
        run: |
          cd docs
          make html latexpdf

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: docs/build/**
