name: Build (MacOS)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  macos-build:
    name: Build LibRapid on MacOS
    runs-on: macos-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      # Download an OpenBLAS build
      - name: Download OpenBLAS Build
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-openblas.yaml
          workflow_conclusion: success
          name: OpenBLAS on macos-latest
          path: src/librapid/openblas_install

      - name: Build LibRapid
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DLIBRAPID_BUILD_EXAMPLES=on -DLIBRAPID_BUILD_TESTS=on -DLIBRAPID_USE_MULTIPREC=on
          cmake --build . --config Release
        env:
          CC: gcc-11
          CXX: g++-11
          LIBRAPID_NO_ARCH: yes

      - name: Run Tests
        run: |
          ctest -C Release -VV