on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  carbonate:
    runs-on: ubuntu-latest
    name: Generate beautiful images for code blocks present in issues
    steps:
      - name: Clone supercharge website repository
        uses: actions/checkout@v2
    
      - name: Checkout Carbonite
        uses: actions/checkout@master
        with:
          repository: callmekatootie/carbonate

      - name: Generate beautiful images for code blocks present in issues
        uses: ./carbonite
        id: carbonate
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          imgur-client-id: ${{ secrets.IMGUR_CLIENT_ID }}
