name: Code Coverage

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: Code Coverage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Compile LibRapid
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_COVERAGE=on -DLIBRAPID_BUILD_TESTS=on -DCMAKE_BUILD_TYPE=Debug
          cmake --build .
        env:
          CC: gcc-9
          CXX: g++-9

      - name: Run Code Coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true

      - name: Upload Code Coverage Results
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
