name: Code Coverage

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: Code Coverage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Run Code Coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true
