name: Compile LibRapid

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  compile:
    name: ${{ matrix.os }} with ${{ matrix.compiler.cxx }} (BLAS ${{ matrix.blas }} | MPFR ${{ matrix.mpfr }})
    runs-on: ${{ matrix.os }}
  
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang-12
            cxx: clang-12
            blas: on
            mpfr: on

          - os: ubuntu-latest
            cc: clang-13
            cxx: clang-13
            blas: on
            mpfr: on

          - os: ubuntu-latest
            cc: clang-14
            cxx: clang-14
            blas: on
            mpfr: on

          - os: ubuntu-latest
            cc: gcc-9
            cxx: g++-9
            blas: on
            mpfr: on

          - os: ubuntu-latest
            cc: gcc-10
            cxx: g++-10
            blas: on
            mpfr: on

          - os: ubuntu-latest
            cc: gcc-11
            cxx: g++-11
            blas: on
            mpfr: on

          - os: macos-latest
            cc: clang
            cxx: clang
            blas: on
            mpfr: on

          - os: macos-latest
            cc: gcc-11
            cxx: g++-11
            blas: on
            mpfr: on

          - os: windows-latest
            cc: msvc
            cxx: msvc
            blas: on
            mpfr: on

    steps:
      - name: Checkout LibRapid
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DLIBRAPID_BUILD_EXAMPLES=on -DLIBRAPID_BUILD_TESTS=on -DLIBRAPID_GET_BLAS=${{ matrix.blas }} -DLIBRAPID_USE_MULTIPREC=${{ matrix.mpfr }}
          cmake --build . --config Release
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}

      - name: Run Tests
        run: |
          cd build
          cd librapid
          ctest -C Release
          