name: "Create Release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  workflow_call:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout LibRapid
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Zip Source Code
        run: |
          zip -r librapid.zip ../librapid

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            librapid.zip
            README.md
            LICENSE
            version.txt
            SECURITY.md
            CONTRIBUTING.md
            CODE_OF_CONDUCT.md
            CITATION.cff
