name: Run Qodana

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  compile:
    name: Run Qodana on LibRapid
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LibRapid
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Qodana Scan
          uses: JetBrains/qodana-action@main
          env:
            QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
